name: build-env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - jupyter_server
  - jupyterlite-core >=0.6
  - jupyterlite-xeus >=4
  - catppuccin-jupyterlab
  - pip:
    - jupyterlab-night
    - jupyterlab_miami_nights
    - JLDracula
    - jupyterlab-language-pack-pt-BR
